import { Verdict, VerdictMeta } from '../types';

const META: Record<Verdict, VerdictMeta> = {
  AI_GENERATED: {
    label: 'AI Generated',
    color: '#ef4444',
    bgClass: 'bg-red-500/10',
    borderClass: 'border-red-500/30',
    textClass: 'text-red-400',
    icon: 'Bot',
    description: 'This image was almost certainly generated by AI',
  },
  LIKELY_AI: {
    label: 'Likely AI',
    color: '#f97316',
    bgClass: 'bg-orange-500/10',
    borderClass: 'border-orange-500/30',
    textClass: 'text-orange-400',
    icon: 'AlertTriangle',
    description: 'Strong indicators suggest this image is AI-generated',
  },
  UNCERTAIN: {
    label: 'Uncertain',
    color: '#f59e0b',
    bgClass: 'bg-amber-500/10',
    borderClass: 'border-amber-500/30',
    textClass: 'text-amber-400',
    icon: 'HelpCircle',
    description: 'Mixed signals — could be AI or human-created',
  },
  LIKELY_REAL: {
    label: 'Likely Real',
    color: '#84cc16',
    bgClass: 'bg-lime-500/10',
    borderClass: 'border-lime-500/30',
    textClass: 'text-lime-400',
    icon: 'ImageIcon',
    description: 'Most indicators suggest this is a real photograph',
  },
  REAL: {
    label: 'Real Photo',
    color: '#22c55e',
    bgClass: 'bg-green-500/10',
    borderClass: 'border-green-500/30',
    textClass: 'text-green-400',
    icon: 'ShieldCheck',
    description: 'This image appears to be an authentic photograph',
  },
};

export function getVerdictMeta(verdict: Verdict): VerdictMeta {
  return META[verdict];
}

export function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
}

export function formatMs(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  return `${(ms / 1000).toFixed(1)}s`;
}

export function resizeImage(file: File, maxDim = 1200): Promise<File> {
  return new Promise((resolve) => {
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d')!;
    const img = new Image();
    const url = URL.createObjectURL(file);

    img.onload = () => {
      URL.revokeObjectURL(url);
      let { width, height } = img;
      if (width > maxDim || height > maxDim) {
        if (width > height) {
          height = Math.round((height / width) * maxDim);
          width = maxDim;
        } else {
          width = Math.round((width / height) * maxDim);
          height = maxDim;
        }
      }
      canvas.width = width;
      canvas.height = height;
      ctx.drawImage(img, 0, 0, width, height);
      canvas.toBlob(
        (blob) => {
          if (!blob) return resolve(file);
          resolve(new File([blob], file.name, { type: file.type || 'image/jpeg' }));
        },
        file.type || 'image/jpeg',
        0.9
      );
    };
    img.onerror = () => resolve(file);
    img.src = url;
  });
}
